### ISSUE TITLE
$coding_font  설정이 안먹는 문제

### ISSUE THREAD

**Issue by honggaruy** [johngrib/johngrib-jekyll-skeleton#18]
* 문제 상황
/css/main.scss 에 `$coding-font` 변수가 있어 이곳에 폰트를 추가하고 이곳에 설정 했지만 적용안됨.
참고링크: [https://github.com/wan2land/d2coding](https://github.com/wan2land/d2coding)
```scss
// /css/main.scss에 다음과 같이 작성
@import url("//cdn.jsdelivr.net/gh/wan2land/d2coding/d2coding-full.css")
$coding-font: 'D2Coding', Consolas, "Courier New", Courier;
```
---
* 상황 분석 
 /_scss/_base.css 에서 다음과 같이 설정하고 있지만...

```scss
code,pre {
    font-family: $coding-font;
}
```
/_scss/_sytax.scss 에서 다음과 같이 중복 설정중임.
```scss
code {
    font-family: Consolas, "Courier New", Courier;
    a { ... }
}
```
---
* 결론
결과적으로 main.scss  에서 @import 순서상 뒤쪽에 있는 _syntax.scss 의 설정이 최종적으로 적용되어 $coding-font의 값이 적용안됨.
---

제 사이트에서는 수정했지만 스켈레톤에도 적용되어야 할듯하여 이슈등록합니다.  두부분중 어느곳을 수정해야 할까요?
